version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.77.1
    steps:
      - checkout
      - run:
          name: Run cargo command
          command: cargo run

workflows:
  build_now:
    jobs:
      - build
