version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.77.1
    steps:
      - checkout
      - run:
          name: Run cargo command
          command: cargo run

  test:
    docker:
      - image: cimg/rust:1.77.1
    steps:
      - checkout
      - run:
          name: Run cargo test
          command: cargo test

  deploy:
    docker:
      - image: cimg/rust:1.77.1
    steps:
      - run: echo "Deploying to production server"
    filters:
      branches:
        only:
          - main

workflows:
  build_now:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
